### ISSUE TITLE
react-modal issue

### ISSUE THREAD

**Issue by thenarain** [reactjs/react-modal#1046]
### Cannot read properties of undefined (reading 'Component') in react-modal:

react-modal.min.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (react-modal.min.js:34:9446)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:4246)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:3589)
    at n (react-modal.min.js:1:450)
    at react-modal.min.js:1:1250
    at react-modal.min.js:1:1259
    at react-modal.min.js:1:290
    at react-modal.min.js:1:312

### Screenshots of issue :
![Screenshot from 2024-04-18 14-43-45](https://github.com/reactjs/react-modal/assets/52527576/a73bbfe3-7a2d-4dd4-ae64-973c033e40a4)

### Additional notes:
##react-modal": "^3.16.1" and react": "^18.2.0

**Comment by babu-izhan-5001312** [comment]
Any solution for this, I am having the same error

##react-modal": "^3.16.1" and react": "^18.2.0
