### ISSUE TITLE
npm test is broken

### ISSUE THREAD

**Issue by saradacp** [reactjs/react-modal#317]
### Summary:
27 01 2017 18:42:14.064:ERROR [config]: Invalid config file!
  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.parseConfig (/Users/scheru1/workspace/github/opensource/react-modal/node_modules/karma/lib/config.js:344:22)
    at new Server (/Users/scheru1/workspace/github/opensource/react-modal/node_modules/karma/lib/server.js:56:20)
    at Object.exports.run (/Users/scheru1/workspace/github/opensource/react-modal/node_modules/karma/lib/cli.js:280:7)
    at Object.<anonymous> (/Users/scheru1/workspace/github/opensource/react-modal/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
npm ERR! Test failed.  See above for more details.
### Steps to reproduce:

 1. npm test 
 2.
 3.

### Expected behavior:
Tests should run without error

**Comment by claydiffrient** [comment]
@saradacp You'll need to use a newer version of Node.  You shouldn't have any problems with `npm test` when running on Node v6 or v7.
