### ISSUE TITLE
MeteorJS compatibility: "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by mbrookes** [reactjs/react-modal#73]
Totally understand if this is out of scope, but I was hoping to use with Meteor (which now supports React). 

As soon as react-modal is added to the project (before any other code changes) I get this error. Full stack trace below:

```
W20150927-22:54:50.503(1)? (STDERR) /Users/mbrookes/.meteor/packages/meteor-tool/.1.1.8.1nd2ri6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150927-22:54:50.503(1)? (STDERR)                         throw(ex);
W20150927-22:54:50.503(1)? (STDERR)                               ^
W20150927-22:54:50.517(1)? (STDERR) ReferenceError: document is not defined
W20150927-22:54:50.517(1)? (STDERR)     at Object.<anonymous> (node_modules/react-modal/lib/helpers/ariaAppHider.js:1:1)
W20150927-22:54:50.517(1)? (STDERR)     at s (../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20150927-22:54:50.518(1)? (STDERR)     at ../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
W20150927-22:54:50.518(1)? (STDERR)     at Object.<anonymous> (node_modules/react-modal/lib/components/Modal.js:4:1)
W20150927-22:54:50.518(1)? (STDERR)     at Object.../helpers/ariaAppHider (node_modules/react-modal/lib/components/Modal.js:82:1)
W20150927-22:54:50.518(1)? (STDERR)     at s (../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20150927-22:54:50.518(1)? (STDERR)     at ../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
W20150927-22:54:50.518(1)? (STDERR)     at Object../components/Modal (node_modules/react-modal/lib/index.js:1:1)
W20150927-22:54:50.518(1)? (STDERR)     at s (../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)
W20150927-22:54:50.518(1)? (STDERR)     at ../../../../../../.meteor/packages/cosmos_browserify/.0.7.0.5ftnjc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1
```

Any help appreciated!

**Comment by wubotao** [comment]
The same issue.

**Comment by ghislaindj** [comment]
You can try this solution : https://github.com/rackt/react-modal/pull/70

**Comment by claydiffrient** [comment]
There hasn't been much traction on this issue in over a year.  I'm assuming that this is no longer an issue, especially considering #70 was merged.  If it is, please feel free to re-open.
