### ISSUE TITLE
Cannot register modal instance that's already open

### ISSUE THREAD

**Issue by Hainesy** [reactjs/react-modal#808]
### Summary:
When a modal is open, double-clicking on the background overlay results in the modal disappearing then quickly reappearing again with the following warning in the console:

```react_devtools_backend.js:6 React-Modal: Cannot register modal instance that's already open 
    at ModalPortal (http://localhost:4500/static/js/0.chunk.js:60569:5)
    at Modal (http://localhost:4500/static/js/0.chunk.js:60212:5)```

**Comment by Hainesy** [comment]
Managed to get around the issue by adding `pointer-events: none` to `.ReactModal__Overlay--before-close`.

**Comment by diasbruno** [comment]
@Hainesy hmm...double click should only close the modal. Do you have on your handlers anything like `openModal = !openModal`?

**Comment by diasbruno** [comment]
Perhaps we are calling your handler twice and this is triggering this behavior.

**Comment by rahul-desai3** [comment]
I am getting same error even after setting `pointer-events: none`  as mentioned above

**Comment by luis-antonio-ac** [comment]
When I click once outside the modal to close it I get:
`React-Modal: Cannot register modal instance that's already open`
and when I click outside the modal again I get:
`portalOpenInstances.js:33 React-Modal: Unable to deregister [object Object] as it was never registered`
and then the modal is closed

**Comment by Hainesy** [comment]
I agree this is still a problem

**Comment by timothymalcham** [comment]
I am now getting this error after upgrading to React 18. Prior to doing the upgrade, I did not see this error: `React-Modal: Cannot register modal instance that's already open`. Does anybody have any idea of what might have changed?

**Comment by pioferen** [comment]
This issue still occurs, I'm using version 3.5.1

**Comment by diasbruno** [comment]
Version 3.15.1 was released. Is this happening on this version?

**Comment by pioferen** [comment]
> Version 3.15.1 was released. Is this happening on this version?

Yes, but I think it occurs only in development mode with react 18 and enabled StrictMode https://github.com/reactwg/react-18/discussions/19

**Comment by diasbruno** [comment]
Hmmm...this is interesting...could you please help creating a reproducible example?

**Comment by pioferen** [comment]
> Hmmm...this is interesting...could you please help creating a reproducible example?

here: https://stackblitz.com/edit/nextjs-aznh2l?file=pages%2Findex.js

without `modalIsOpen &&` error doesn't occur

**Comment by diasbruno** [comment]
cc @Hainesy @timothymalcham @rahul-desai3 @luis-antonio-dev

**Comment by Brhernann** [comment]
same issue 

![image](https://user-images.githubusercontent.com/18491638/169229157-c3046e2e-59c1-4fc4-b0bd-37186a40f3e0.png)

**Comment by Brhernann** [comment]
Same warning

![image](https://user-images.githubusercontent.com/18491638/169229347-eb531575-7f14-41b4-b9c2-ddd624d1bed0.png)

**Comment by deep-cognite** [comment]
Facing the same issue for one of my modals after upgrading to React 18. Any fixes to this?

**Comment by lassonico** [comment]
¿En definitiva no hay solucion?

**Comment by oroszi1mark** [comment]
Using react-modal with [nice-modal-react](https://github.com/eBay/nice-modal-react) makes for a handy combination in my opinion, but unfortunately nice-modal-react also uses conditional rendering. The console warning can be triggered in [this example](https://codesandbox.io/s/react-18-x-react-modal-x-nice-modal-react-2cvlmq).

**Comment by Phanabani** [comment]
I was having this error (react-modal 3.15.1, React 18.2.0), and after a lot of frustration, found out that my problem was caused by using [`React.StrictMode`](https://reactjs.org/docs/strict-mode.html) in my root element, which apparently double-invokes some lifecycle methods in development mode (not production, though). As of now, this behavior is documented in the StrictMode docs -- search for "double-invoking the following functions".

I noticed an effect was being called twice and found [this answer](https://stackoverflow.com/a/60619061/2933708), which also referenced [this answer](https://stackoverflow.com/a/61897567/2933708) which has more info about the double rendering of `StrictMode`.

It seems like this is harmless in my case because the only visible issue is the warning in console (modals are still displaying fine), but if anyone has a suggestion for suppressing the warning, I'd appreciate it!

**Comment by diasbruno** [comment]
Why don't you fix it, @mleister97?

**Comment by honeymaro** [comment]
I have the same issue.

no conditional rendering,
no strict mode.

react-modal `3.16.1`,
react `18.2.0`

**Comment by diasbruno** [comment]
This seem to be a mem leak on the [src/helpers/portalOpenInstances.js](https://github.com/reactjs/react-modal/blob/master/src/helpers/portalOpenInstances.js), but it's most likely that this is cause by something that is removing the modal without unmounting it.

**Comment by rodriguezmoradiego15** [comment]
We Can't use: 
`{modalIsOpen && (......)`
The best way to use that  is creating a component where we have all the code that we need, a componet seems something like this:

`<Modal 
                isOpen={modal} 
                style={customStyles}
            >
                <ModalProducto />
            </Modal>`
and ModalProducto.jsx is something like this:
`export default function ModalProducto() {
  return (
    <div>ModalProducto</div>
  )
}
`

That way works for me

No podemos usar:
`{modalIsOpen && (......)`
Lo que se debe hacer es crear un componente con toda la lógica que necesitamos, algo parecido a lo siguiente: 
`<Modal 
                isOpen={modal} 
                style={customStyles}
            >
                <ModalProducto />
            </Modal>`

y ModalProducto.jsx es algo como lo siguiente:
`export default function ModalProducto() {
  return (
    <div>ModalProducto</div>
  )
}
`
Esa es la solución.

**Comment by webexpert821** [comment]
This error is occurring because you haven't declared the CSS for the modal. If you declare the CSS in a global file such as index.css, the error will not happen.

.mymodal {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

  border: 1px solid #ccc;
  background: #fff;
  overflow: auto;
  border-radius: 4px;
  outline: none;
  padding: 20px;
}

.myoverlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.75);
}

.ReactModal__Overlay {
  opacity: 0;
  transition: opacity 500ms ease-in-out;
}

.ReactModal__Overlay--after-open {
  opacity: 1;
}

.ReactModal__Overlay--before-close {
  opacity: 0;
}

**Comment by brianpeiris** [comment]
If it helps, I was able to reproduce this issue with minimal changes to the `simple_usage` example in this repo.

The steps I took:

1. Upgrade to React 18
2. Add `React.StrictMode` to the example
3. Use `createRoot` instead of `ReactDOM.render`
4. Set `isOpen` to `true` by default

The warning then appears in the console when you open the example.

Here is the diff: https://github.com/reactjs/react-modal/compare/master...brianpeiris:react-modal:register-warning

I did not have to use conditional rendering to reproduce this issue, and more people will run into it as people adopt React 18. Notably, modern tooling, like Vite, enables StrictMode by default.

**Comment by diasbruno** [comment]
@brianpeiris Yep, this is not just a case of conditional rendering (but kinda related). 

The problem seems to be a new feature of react 18 where it can keep some components alive to make some rendering optimizations. But this causes all sorts of problems because react-modal is a stateful component that needs to deal with subtrees.

**Comment by Hebzebba** [comment]
> > Version 3.15.1 was released. Is this happening on this version?
> 
> Yes, but I think it occurs only in development mode with react 18 and enabled StrictMode [reactwg/react-18#19](https://github.com/reactwg/react-18/discussions/19)

Doing this fix the issue for me

**Comment by berryboylb** [comment]
I don't 

> I'm flagging this as `hardcore`. I did a little investigation, don't have time to fully jump into this, and, this is super annoying.
> 
> It's all about the new react version and this component `src/components/Modal.js`, specially when the component is unmounted.
> 
> If you want to be at the 1% top react dev, this is a great challenge.
> 
> You need to:
> 
> * Check the places where we (de)register the modal (mount and unmount)
> * Make sure react calls unmount when it is supposed to (this is actually a problem since react 16.3+)
> 
> This is enough information to start digging in.
> 
> If anyone wants to fight with this, let me know. For any other questions, I'll be here to help.

I don't want to be a top react dev, just fix the issue please.

**Comment by diasbruno** [comment]
@berryboylb :crying_cat_face:

**Comment by shulcsm** [comment]
Issue is here:
https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L136

When strict mode unmounts  `isOpen` is not yet initialized so it's not de-registering the modal correctly so it leaks instances and focus handlers.

This "works"
```tsx
  if (this.state.isOpen || (typeof this.state.isOpen === 'undefined' && this.props.isOpen)) {
    this.afterClose();
  }
```
But honestly whole thing should be rewritten.

**Comment by diasbruno** [comment]
@shulcsm You can rewrite if you want. We will be really happy.

This library remains working on really dated versions of react to maintain backwards-compatibility. It's great, but also has some drawback...

Feel free to share some ideas regarding this.

**Comment by doeg** [comment]
Hey @diasbruno, want me to take this one? Feel free to assign it to me if so. 🙇

**Comment by ADTC** [comment]
This happened to me, _not because of conditional rendering,_ but because I was forcing the modal to be already open upon page load:

```ts
  const [isOpen, setIsOpen] = useState(true)
```

The fix is to use an effect hook to open the modal _after_ the component has loaded:

```ts
  const [isOpen, setIsOpen] = useState(false)

  useEffect(() => setIsOpen(true), [])
```

This will help force the modal to be open as soon as the page loads, but avoids the warning _"Cannot register modal instance that's already open"_.

**Comment by tacticSugar** [comment]
Conditional rendering causes the problem, true.
Change
`{isOpen && <Modal isOpen={isOpen}/>}`
to just 
`<Modal isOpen={isOpen}/>`

you can use dynamic (react or next)

**Comment by roztownsend** [comment]
Is there a reason this issue would be occurring only if you use CSS classes for styling? Everything works fine for me with the default styles or writing a "customStyles" object, but if I try to use the className and overlayClassName props in my modal, I get this error.

**Comment by diasbruno** [comment]
@roztownsend Can you please create an example to show this issue?

**Comment by diasbruno** [comment]
@roztownsend No problem.

If anyone can create an example to show this issue, it would be appreciated. 

One problem is well-known, it's related to conditional rendering. If anyone has a different set up, please create an example to help reproducing the issue.

**Comment by ADTC** [comment]
@diasbruno can't do an example right now, but I have mentioned in [my previous comment](https://github.com/reactjs/react-modal/issues/808#issuecomment-2040536762) that opening a modal on page load cannot be done with state preset to true. It should be preset to false, then an effect should toggle it to true.

I think that qualifies as a different setup.

**Comment by diasbruno** [comment]
@ADTC No problem. That's a nice workaround. 

It would be nice to avoid the useEffect though.

**Comment by mdmower-csnw** [comment]
> One problem is well-known, it's related to conditional rendering. If anyone has a different set up, please create an example to help reproducing the issue.

@diasbruno - This is very close to conditional rendering, but the warning can also be reproduced by incrementing the `key` prop on a modal. I do this when a form in the modal has uncontrolled inputs and needs to be reset when the modal is dismissed and then reopened. I've created a minimal sample at: https://github.com/mdmower-csnw/react-modal-key/blob/main/src/main.jsx .
