### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by finleyowen** [reactjs/react-modal#898]
When trying to build an app with this dependency, react logs the following error to the console. I've set the `appElement` to `'#root'` in my `index.js` file and tried using `ariaHideApp={false}`, but neither have solved the error.
```
Uncaught TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (react-modal.min.js:34)
    at n (react-modal.min.js:1)
    at Object.<anonymous> (react-modal.min.js:13)
    at n (react-modal.min.js:1)
    at Object.<anonymous> (react-modal.min.js:13)
    at n (react-modal.min.js:1)
    at react-modal.min.js:1
```

**Comment by diasbruno** [comment]
@finleyowen Which version are you using?

**Comment by cbisum** [comment]
Same issue i am using version 3.14.3

**Comment by diasbruno** [comment]
If you are using `<Modal appElement={node} />`, `node` needs to be a dom node...not a string. Can you check if this is the issue?

**Comment by MadhavKauntia** [comment]
I'm facing a similar issue. Here are the attributes I'm passing on to ReactModal.
```js
<ReactModal
        ariaHideApp={false}
        isOpen={showLoginModal}
        onRequestClose={closeModal}
        className="bg-whitish w-[80%] h-[70%] md:w-[50%] md:h-[30%] rounded-md absolute top-[50%] left-[50%] transform -translate-x-1/2 -translate-y-1/2 border border-blackish flex flex-col justify-center items-center"
>
```

Here is the error I'm getting.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (react-modal.min.js:34:9446)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:4246)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:3589)
    at n (react-modal.min.js:1:450)
    at react-modal.min.js:1:1250
    at react-modal.min.js:1:1259
    at react-modal.min.js:1:290
    at react-modal.min.js:1:312
```

Can someone help me out with this?

**Comment by MadhavKauntia** [comment]
@diasbruno 3.15.1

**Comment by haratmalli** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (react-modal.min.js:34:9446)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:4246)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:3589)
    at n (react-modal.min.js:1:450)
    at react-modal.min.js:1:1250
    at react-modal.min.js:1:1259
    at react-modal.min.js:1:290
    at react-modal.min.js:1:312
    
    version is: "react-modal": "^3.16.1",

**Comment by diasbruno** [comment]
If you want to make a reproducible example for this...one can create a new react project and add `react` and `react-modal` (with some combination of versions).

This should trigger the issue, and, we can finally address it.

**Comment by diasbruno** [comment]
As people have found out, if you delete `node_modules` and reinstall everything, it works. It seems a cache issues.
Please, feel free to reopen if that's not your case.

**Comment by ShivamDev412** [comment]
> As people have found out, if you delete `node_modules` and reinstall everything, it works. It seems a cache issues. Please, feel free to reopen if that's not your case.

It still don't work having same issue my react-modal version "react-modal": "^3.16.1" and react version "react": "^18.2.0",
error. "react-modal.min.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (react-modal.min.js:34:9446)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:4246)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:3589)
    at n (react-modal.min.js:1:450)
    at react-modal.min.js:1:1250
    at react-modal.min.js:1:1259
    at react-modal.min.js:1:290
    at react-modal.min.js:1:312
"

**Comment by thenarain** [comment]
react-modal.min.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
    at Object.<anonymous> (react-modal.min.js:34:9446)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:4246)
    at n (react-modal.min.js:1:450)
    at Object.<anonymous> (react-modal.min.js:13:3589)
    at n (react-modal.min.js:1:450)
    at react-modal.min.js:1:1250
    at react-modal.min.js:1:1259
    at react-modal.min.js:1:290
    at react-modal.min.js:1:312
    
    same issue I am getting. react-modal version "react-modal": "^3.16.1" and react version "react": "^18.2.0",
    
    
    
![Screenshot from 2024-04-18 14-43-45](https://github.com/reactjs/react-modal/assets/52527576/e82fa146-daaf-47cc-a6b6-6c42e6fab718)
